SET 'auto.offset.reset'='earliest';
CREATE TABLE AIRCRAFT_TABLE_KEY WITH (KAFKA_TOPIC='AIRCRAFT_KEY',VALUE_FORMAT='AVRO',KEY='type');
CREATE STREAM TRAFFIC_NOKEY WITH (KAFKA_TOPIC='traffic',VALUE_FORMAT='AVRO');
CREATE STREAM TRAFFIC_KEY AS SELECT * FROM TRAFFIC_NOKEY PARTITION BY type;
CREATE STREAM TRAFFIC_ENRICHED WITH (VALUE_FORMAT='JSON')  AS select t.Date,t.Vol,t.Depart,t.Arrivee,t.Appareil,t.Distance,t.type,a.Aircraft,a.Longueur,a.Autonomie,a.Passagers from TRAFFIC_KEY t LEFT OUTER JOIN AIRCRAFT_TABLE_KEY a  ON t.type = a.type;
